version: 1.0
provider:
  name: openfaas
functions:
  openfaas-opennsfw:
    lang: dockerfile
    handler: ./openfaas-opennsfw
    image: servernull/openfaas-opennsfw:0.1.0
    environment:
      read_timeout: 120
      write_timeout: 120
      exec_timeout: 120
